-- Redacted example data derived from the audit structure of the
-- March 19, 2026 reference run. Shared drive names, item paths,
-- file IDs, permission IDs, and identities have been replaced with
-- placeholders, while the permission patterns and row shapes remain
-- representative of a successful `augmented` mode audit.

CREATE OR REPLACE TABLE shared_drive_inventory_example AS
SELECT *
FROM (
  VALUES
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_001',
      'External collaboration',
      'Shared Drive Alpha / External collaboration',
      'folder',
      'application/vnd.google-apps.folder',
      TRUE,
      FALSE,
      '["drive_redacted_alpha"]',
      TIMESTAMPTZ '2024-08-03 09:10:00+10:00',
      TIMESTAMPTZ '2026-03-18 16:21:00+11:00',
      NULL,
      FALSE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_002',
      'Project Atlas',
      'Shared Drive Alpha / External collaboration / Project Atlas',
      'folder',
      'application/vnd.google-apps.folder',
      TRUE,
      FALSE,
      '["item_alpha_001"]',
      TIMESTAMPTZ '2024-08-03 09:12:00+10:00',
      TIMESTAMPTZ '2026-03-19 14:05:00+11:00',
      NULL,
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_003',
      'Drawings',
      'Shared Drive Alpha / External collaboration / Project Atlas / Drawings',
      'folder',
      'application/vnd.google-apps.folder',
      TRUE,
      FALSE,
      '["item_alpha_002"]',
      TIMESTAMPTZ '2024-08-03 09:15:00+10:00',
      TIMESTAMPTZ '2026-03-18 10:42:00+11:00',
      NULL,
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_004',
      'IFC set.pdf',
      'Shared Drive Alpha / External collaboration / Project Atlas / Drawings / IFC set.pdf',
      'file',
      'application/pdf',
      FALSE,
      FALSE,
      '["item_alpha_003"]',
      TIMESTAMPTZ '2024-08-04 11:05:00+10:00',
      TIMESTAMPTZ '2026-03-17 08:33:00+11:00',
      4321987,
      FALSE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_005',
      'Handover checklist',
      'Shared Drive Alpha / External collaboration / Project Atlas / Handover checklist',
      'file',
      'application/vnd.google-apps.spreadsheet',
      FALSE,
      FALSE,
      '["item_alpha_002"]',
      TIMESTAMPTZ '2024-08-06 15:20:00+10:00',
      TIMESTAMPTZ '2026-03-19 13:11:00+11:00',
      NULL,
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_beta',
      'Shared Drive Beta',
      'item_beta_001',
      'Quality system',
      'Shared Drive Beta / Quality system',
      'folder',
      'application/vnd.google-apps.folder',
      TRUE,
      FALSE,
      '["drive_redacted_beta"]',
      TIMESTAMPTZ '2024-02-10 07:30:00+11:00',
      TIMESTAMPTZ '2026-03-19 09:50:00+11:00',
      NULL,
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_beta',
      'Shared Drive Beta',
      'item_beta_002',
      'Audit working papers',
      'Shared Drive Beta / Quality system / Audit working papers',
      'folder',
      'application/vnd.google-apps.folder',
      TRUE,
      FALSE,
      '["item_beta_001"]',
      TIMESTAMPTZ '2024-03-01 12:00:00+11:00',
      TIMESTAMPTZ '2026-03-18 18:22:00+11:00',
      NULL,
      FALSE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:40+11:00',
      'drive_redacted_beta',
      'Shared Drive Beta',
      'item_beta_003',
      'Procedure register.docx',
      'Shared Drive Beta / Quality system / Procedure register.docx',
      'file',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      FALSE,
      FALSE,
      '["item_beta_001"]',
      TIMESTAMPTZ '2024-05-16 14:45:00+10:00',
      TIMESTAMPTZ '2026-03-16 07:12:00+11:00',
      248192,
      FALSE,
      FALSE
    )
) AS t(
  audit_captured_at,
  shared_drive_id,
  shared_drive_name,
  item_id,
  item_name,
  item_path,
  item_kind,
  item_mime_type,
  item_is_folder,
  item_is_shortcut,
  item_parent_ids_json,
  item_created_time,
  item_modified_time,
  item_size_bytes,
  item_has_augmented_permissions,
  item_inherited_permissions_disabled
);

CREATE OR REPLACE TABLE shared_drive_sharing_audit_example AS
SELECT *
FROM (
  VALUES
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_002',
      'Project Atlas',
      'Shared Drive Alpha / External collaboration / Project Atlas',
      'folder',
      TRUE,
      TRUE,
      'perm_alpha_001',
      'user',
      'writer',
      'consultant.one@partner.example',
      NULL,
      'Consultant One',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_002',
      'Project Atlas',
      'Shared Drive Alpha / External collaboration / Project Atlas',
      'folder',
      TRUE,
      TRUE,
      'perm_alpha_002',
      'user',
      'writer',
      'consultant.two@partner.example',
      NULL,
      'Consultant Two',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_002',
      'Project Atlas',
      'Shared Drive Alpha / External collaboration / Project Atlas',
      'folder',
      TRUE,
      TRUE,
      'perm_alpha_003',
      'user',
      'writer',
      'reviewer@contractor.example',
      NULL,
      'Reviewer',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_003',
      'Drawings',
      'Shared Drive Alpha / External collaboration / Project Atlas / Drawings',
      'folder',
      TRUE,
      TRUE,
      'perm_alpha_004',
      'user',
      'commenter',
      'field.lead@partner.example',
      NULL,
      'Field Lead',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_alpha',
      'Shared Drive Alpha',
      'item_alpha_005',
      'Handover checklist',
      'Shared Drive Alpha / External collaboration / Project Atlas / Handover checklist',
      'file',
      FALSE,
      TRUE,
      'perm_alpha_005',
      'user',
      'writer',
      'handover.coordinator@partner.example',
      NULL,
      'Handover Coordinator',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_beta',
      'Shared Drive Beta',
      'item_beta_001',
      'Quality system',
      'Shared Drive Beta / Quality system',
      'folder',
      TRUE,
      TRUE,
      'perm_beta_001',
      'group',
      'fileOrganizer',
      'quality-drive-admins@company.example',
      NULL,
      'Quality Drive Admins',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_beta',
      'Shared Drive Beta',
      'item_beta_001',
      'Quality system',
      'Shared Drive Beta / Quality system',
      'folder',
      TRUE,
      TRUE,
      'perm_beta_002',
      'user',
      'fileOrganizer',
      'quality.manager@company.example',
      NULL,
      'Quality Manager',
      TRUE,
      FALSE
    ),
    (
      TIMESTAMPTZ '2026-03-19 19:21:50+11:00',
      'drive_redacted_beta',
      'Shared Drive Beta',
      'item_beta_001',
      'Quality system',
      'Shared Drive Beta / Quality system',
      'folder',
      TRUE,
      TRUE,
      'perm_beta_003',
      'user',
      'fileOrganizer',
      'auditor@company.example',
      NULL,
      'Auditor',
      TRUE,
      FALSE
    )
) AS t(
  audit_captured_at,
  shared_drive_id,
  shared_drive_name,
  item_id,
  item_name,
  item_path,
  item_kind,
  item_is_folder,
  item_has_augmented_permissions,
  permission_id,
  permission_type,
  permission_role,
  permission_email_address,
  permission_domain,
  permission_display_name,
  permission_is_direct,
  permission_is_inherited_only
);

SELECT 'inventory_rows' AS metric, COUNT(*) AS value
FROM shared_drive_inventory_example
UNION ALL
SELECT 'sharing_rows' AS metric, COUNT(*) AS value
FROM shared_drive_sharing_audit_example
UNION ALL
SELECT 'shared_drives' AS metric, COUNT(DISTINCT shared_drive_id) AS value
FROM shared_drive_inventory_example;
